// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gregs_Auto.Domain.EntityModels;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int VehicleId { get; set; }

    public int ServiceId { get; set; }

    public DateTime ScheduledAt { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual Service Service { get; set; }
}
