// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gregs_Auto.Domain.EntityModels;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public int CustomerId { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public short Year { get; set; }

    public string Vin { get; set; }

    public string LicensePlate { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
}
