// <auto-generated> This file is meant to be regenerated by EF Core Power Tools once the
// database schema exists. Add DbSet properties and OnModelCreating mappings here as
// entities are scaffolded. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace Gregs_Auto.DAL.Context;

public partial class GregsAutoContext : DbContext
{
    public GregsAutoContext(DbContextOptions<GregsAutoContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
